### ISSUE TITLE
Testing with GAP development version

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/agt#1]
Please add this package to 

https://github.com/gap-infra/gap-docker-pkg-tests-master-devel/blob/master/.travis.yml

and 

https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/blob/master/.travis.yml

- this will allow us to test how your package works under GAP's master and stable-4.11 branches

**Comment by rhysje00** [comment]
Done by Alex:

gap-infra/gap-docker-pkg-tests-master-devel@3896c6c725110890acf181a1c37b6ecb096cfc4e 
gap-infra/gap-docker-pkg-tests-stable-4.11-devel@844a7b3e30992b9beecae10c0581839b3adac0e0
