### ISSUE TITLE
Mismatch between .gitignore and repository

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/agt#10]
Your .gitignore among other things lists these files:
```
/srglib/Validated.g
/srglib/NotInvalidated.g
/srglib/Enumerated.g
/srglib/BrouwerParametersold.g
/srglib/Available.g
/srglib/SpenceFileToGAP.m
```
Yet these files are actually in the repository. That makes no sense: either those files should be removed from the repository; or else these lines be removed from `.gitignore`.

BTW, if you simply don't want these files to be in releases, you can edit the `.release` script to delete them during the release process (assuming you are using ReleaseTools to make releases)

**Comment by rhysje00** [comment]
These files are not needed, so I have removed them f62eb37
