### ISSUE TITLE
AGT 0.3 tarball contains broken symlink

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/agt#15]
Specifically:
```
$ ls -al doc/mathjax
lrwxr-xr-x 1 mhorn staff 29 Dec 14 16:54 doc/mathjax -> /usr/share/javascript/mathjax
```

**Comment by fingolfin** [comment]
@rhysje00 how do you create the release tarballs? I am pretty sure the problem would not have happened if you were using [ReleasTools](https://github.com/gap-system/ReleaseTools) (if you *are* using ReleaseTools, I'd be really curious to know how this could happen)

**Comment by rhysje00** [comment]
@fingolfin I did use ReleaseTools, and followed the instructions given in the README file. Do you have any idea how I could have done this?

**Comment by fingolfin** [comment]
Oh wow, that's fascinating then.

To get started, could you please let me know which version of ReleaseTools you were using -- while I can't think of any recent or past change that would affect this, it would help me to have as a baseline for debugging (so, if you are using it from a `git` clone of the ReleaseTools repository, just tell me the commit. If you have downloaded and copied the script somewhere, perhaps you can email me a copy).

Next, what OS did you run it on?

Finally, how was GAP installed on that computer? I.e., via some package manager, or by downloading the GAP source tarball and compiling, or ... ?

**Comment by rhysje00** [comment]
Actually, I recently had to replace my hard drive and think I was fairly up to date when I made the release.

ReleaseTools commit: gap-system/ReleaseTools@f624c1d661e6e7708321c97d82fb139062089966
OS: Ubuntu 22.04.1 LTS
GAP version: 4.12.1

I downloaded the GAP tarball and compiled as described on the website.

**Comment by fingolfin** [comment]
OK, that's a good baseline. Unfortunately it gives me no idea whatsoever how it could possibly end up with that weird symlink `doc/mathjax` in the tarball? I mean, *something* must have created it there, but what?

Just to test, is there a file `/usr/share/javascript/mathjax` on your computer?

**Comment by fingolfin** [comment]
Oh. So I searched for packages containing a file named `mathjax` in Ubuntu, via [this link](https://packages.ubuntu.com/search?searchon=contents&keywords=mathjax&mode=exactfilename&suite=kinetic&arch=any) and it brought up a bunch of GAP packages!

Could it be that on your computer you had (or still have) a version of GAP installed via the Ubuntu package manager? Unfortunately this kind of GAP is modified and in some cases these modifications are problematic. This might be one more instance of this.

So my guess is that somehow stuff from that GAP installation got mixed up with the GAP you installed by downloading the GAP tarball, and this wrecked things. I still don't know *how*, partly because I also don't know why the Debian/Ubuntu package creates these `mathjax` files in the first place. (UPDATE: OK, it seems they do this to avoid links to an external URL when viewing HTML files using MathJax in a local browser, see [this patch file](https://sources.debian.org/src/gap-gapdoc/1.6.6-1/debian/patches/lib-mathjax/).

So, solution then: de-install any `gap*` packages installed via the Ubuntu package manager, then make a fresh release.

**Comment by rhysje00** [comment]
You are right, I do have a version of GAP downloaded via the package manager. I guess at some point my curiosity got  the best of me!

I have made the fixes you suggested, and released a new version. The `mathjax` file is not present in the tarball of new version, so hopefully this has worked. Let me know you find any more problems.

**Comment by fingolfin** [comment]
Thanks @rhysje00 version 0.3.1 seems perfect :-)
