### ISSUE TITLE
Website and releases

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/agt#2]
This explains how to do it:
- https://github.com/gap-system/ReleaseTools
- https://github.com/gap-system/GitHubPagesForGAP

**Comment by rhysje00** [comment]
Website setup and first release completed 89a83c8ff56f80899f9daf180ccd792aa7c8e647.

**Comment by olexandr-konovalov** [comment]
@rhysje00 I suggest to replace the URL of the webpage in the README to https://rhysje00.github.io/agt/ (it now points to the repository instead), and also specify the webpage at the repository description at https://github.com/rhysje00/agt. Also, if you're willing to migrate to https://github.com/gap-packages please let me know.

**Comment by rhysje00** [comment]
@alex-konovalov Thank you, I have now done this. If I can get help with the migration process, I am happy to start the migration to gap-package.

**Comment by olexandr-konovalov** [comment]
@rhysje00 I have invited you to https://github.com/orgs/gap-packages/people - when you will accept membership, you should be able to do this - https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by rhysje00** [comment]
@alex-konovalov thanks again. This is done, but I think I need further access rights to change the webpage in the description. Or can you change this?

**Comment by olexandr-konovalov** [comment]
Thanks @rhysje00. I have now made you an admin for this repository, so you have all the same rights as before, and can now make changes.

**Comment by rhysje00** [comment]
@alex-konovalov  Great, thanks a lot.
