### ISSUE TITLE
Redistributing with GAP

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/agt#4]
After #2, add a line to https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList with the URL of PackageInfo.g and email to GAP Support with the suggestion to deposit this package.

**Comment by rhysje00** [comment]
Email sent and pull request made from fork rhysje00/gap-distribution@96c80b964e18d51b657127db460267025a213d4d

**Comment by olexandr-konovalov** [comment]
@rhysje00 thanks. Would be useful to make a new release with recent changes as suggested by @fingolfin

**Comment by rhysje00** [comment]
@alex-konovalov thanks. I have now made a new release with all changes suggested by you and @fingolfin included.

**Comment by fingolfin** [comment]
AGT is being redistributed
