### ISSUE TITLE
Clarify licensing terms

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/agt#8]
The README just refers to "the terms of the GNU General Public License" but does not specify which version. It also points to the `LICENSE` file, which has GPL 3, but it is left unclear whether now GPL 3 is indeed the license, or "GPL 3 or later", or something else. The README.md should make that clear.

In general, I would recommend to use the "... or later" variant as it can help simplify things in the future. Here is the "standard" text for that:
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation, either version 3 of the License, or
> (at your option) any later version.

Also, if this code is entirely written by you, please consider whether "GPL *2* or later" would also be acceptable for you, as that would match the licensing terms of GAP itself and thus make life of downstream packagers easier. That said, it is of course your choice.

Finally, I would appreciate if you were to add a suitable `License` field to `PackageInfo.g`. See e.g. here https://github.com/gap-packages/io/blob/master/PackageInfo.g (any [SPDX](https://spdx.org) license ID is acceptable).

**Comment by rhysje00** [comment]
Thanks for all the advice! I have gone with GPL 2 or later f62eb37

**Comment by fingolfin** [comment]
Thanks!

One unrelated, well-meant suggestion (but feel free to ignore it, this is just meant as a hint based on personal experience): I noticed that the commit you referenced did multiple things: change licensing terms, remove files, but it also modified the function`RegularAdjacencyUpperBound` substantially. The first two changes were mentioned in the commit message, but not the change to `RegularAdjacencyUpperBound`. I would recommend to use separate commits for each such changes, that is a "best practice" which can be very helpful down the road.

**Comment by rhysje00** [comment]
Much appreciated! As a newbie to github, any advice on best practice for github, or practices specific to the gap github community would be very helpful.
